=== Politecnicojic2022-01/Ejercicio6/ListaCursos.dtd
<!ELEMENT ListaCursos (cursos)+>
        <!ELEMENT cursos (alumnos)+>
        <!ELEMENT alumnos (DNI,nombreEstudiante,primerApellidoEstudiante, segundoApellidoEstudiante?, listaAsignaturas)>
        <!ELEMENT DNI (#PCDATA)>
        <!ELEMENT nombreEstudiante (#PCDATA)>
        <!ELEMENT primerApellidoEstudiante (#PCDATA)>
        <!ELEMENT segundoApellidoEstudiante (#PCDATA)>
        <!ELEMENT listaAsignaturas (asignatura)+>
        <!ELEMENT asignatura (nombreAsignatura, profesor)>
        <!ELEMENT nombreAsignatura (#PCDATA)>
        <!ELEMENT profesor (NRP, nombreProfesor, primerApellidoProfesor, segundoApellidoProfesor?)>
        <!ELEMENT NRP (#PCDATA)>
        <!ELEMENT nombreProfesor (#PCDATA)>
        <!ELEMENT primerApellidoProfesor (#PCDATA)>
        <!ELEMENT segundoApellidoProfesor (#PCDATA)>
        <!ATTLIST asignatura codigo CDATA #REQUIRED>

=== Politecnicojic2022-01/Ejercicio6/ListaCursos.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ListaCursos SYSTEM "ListaCursos.dtd">

<ListaCursos>
    <cursos>
        <alumnos>
            <DNI></DNI>
            <nombreEstudiante></nombreEstudiante>
            <primerApellidoEstudiante></primerApellidoEstudiante>
            <segundoApellidoEstudiante></segundoApellidoEstudiante>
            <listaAsignaturas>
                <asignatura codigo="">
                    <nombreAsignatura></nombreAsignatura>
                    <profesor>
                        <NRP></NRP>
                        <nombreProfesor></nombreProfesor>
                        <primerApellidoProfesor></primerApellidoProfesor>
                        <segundoApellidoProfesor></segundoApellidoProfesor>
                    </profesor>
                </asignatura>
            </listaAsignaturas>
        </alumnos>
    </cursos>
</ListaCursos>
